version: "3.7"

services:
  app:
    build: .
    ports:
      - "8090:8090"  # Mapping host port 8090 to container port 8090
    networks:
      - student-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: jitu
      POSTGRES_PASSWORD: 1234  # Corrected environment variable
      POSTGRES_DB: telusko
    ports:
      - "5433:5432"  # Host port 5433 mapped to container port 5432
    networks:
      - student-network

networks:
  student-network:
    driver: bridge
