#version: "3.7"/

services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - student-network
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: jitu
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: telusko
    ports:
      - "5433:5432"
    networks:
      - student-network
    volumes:
      - postgres-s-data:/var/lib/postgresql/data

networks:
  student-network:
    driver: bridge

volumes:
  postgres-s-data
