version: "3.7"

services:
  app:
    build: .
    ports:
      - "9000:9000"  # Map port 9000 of the host to port 9000 of the container
    environment:
      - SPRING_PROFILES_ACTIVE=default
    networks:
      - student-network
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: jitu
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: telusko
    ports:
      - "5433:5432"  # Map host port 5433 to container port 5432
    networks:
      - student-network
    volumes:
      - postgres-s-data:/var/lib/postgresql/data

networks:
  student-network:
    driver: bridge

volumes:
  postgres-s-data:
